### PR TITLE
Sanitize utf-8 in requests. Fixes #302

### LINKED ISSUE #302: [Stacks/dev] ArgumentError: invalid byte sequence in UTF-8
## Backtrace

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/49299/faults/34397275)

### PR DESCRIPTION
**Pull request by jcoyne**

### CODE REVIEW

**Comment by jcoyne** [comment]
Ref: https://github.com/rails/rails/issues/30811

**Comment by aaron-collier** [comment]
Should we have any tests here to make sure this doesn't break anything? I'm assuming it's clean and this ultimately helps, just want to make sure we're good.

**Comment by jcoyne** [comment]
@aaron-collier how would you suggest I test this?

**Comment by aaron-collier** [comment]
@jcoyne - Good question, I'm assuming that adding this effects some change to a problem we saw before that could be verified? Some description to this PR would help as it's been a while ;-)

**Comment by jcoyne** [comment]
No longer an issue since we no longer use Sprockets.

**Pull request closed without merging**
