### PR TITLE
Add missing gems to Gemfile.lock

### PR DESCRIPTION
**Pull request by corylown**

### CODE REVIEW

**Review by jcoyne — APPROVED** [review]

**Review by peetucket — APPROVED** [review]
I wonder why these gems were not added as dependencies in gemfile.lock if they are required by the rails 7 upgrade

**Comment by jcoyne** [comment]
I'm also curious as to what is going on.

**Comment by jcoyne** [comment]
It looks like dependency updates removed it: https://github.com/sul-dlss/stacks/pull/1107/files#diff-89cade48462044ee1b672dc5f4c3ec250fbd29effcd8932096a23c1283c6731fL74

**Comment by peetucket** [comment]
I thought that if a gem (e.g. something in rails 7) needed them again, then the bundle install would have added them into gemfile.lock as dependencies even if they weren't explicitly added in the Gemfile itself.

**Pull request merged**
